
package Vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Graciela
 */
public class FrmCarreras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCarreras.class.getName());

    /**
     * Creates new form FrmCarrera
     */
    public FrmCarreras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carreras");

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Grado"
            }
        ));
        jScrollPane1.setViewportView(tblEstudiantes);
        if (tblEstudiantes.getColumnModel().getColumnCount() > 0) {
            tblEstudiantes.getColumnModel().getColumn(0).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(1).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insertar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     
// Solicita el nombre del estudiante
    String nombre = JOptionPane.showInputDialog("Ingrese el nombre:");
   
// Si el usuario cancela o deja el campo vacío, se detiene la acción
    if (nombre == null || nombre.trim().isEmpty()) return;

    // Solicita el ID del estudiante
    String id = JOptionPane.showInputDialog("Ingrese el ID:");
    if (id == null || id.trim().isEmpty()) return;

    // Solicita el grado del estudiante
    String grado = JOptionPane.showInputDialog("Ingrese el grado:");
    if (grado == null || grado.trim().isEmpty()) return;

    // Obtiene el modelo de la tabla para poder modificar sus datos
    DefaultTableModel model = (DefaultTableModel) tblEstudiantes.getModel();

    // Agrega una nueva fila con los datos ingresados
    model.addRow(new Object[]{nombre, id, grado});
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       // Obtiene el índice de la fila seleccionada
    int filaSeleccionada = tblEstudiantes.getSelectedRow();

    // Verifica si se ha seleccionado alguna fila
    if (filaSeleccionada == -1) {
        
        // Muestra un mensaje si no hay selección
        JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para eliminar.");
        return;
    }

    // Confirma con el usuario antes de eliminar
    int confirmacion = JOptionPane.showConfirmDialog(
        null,
        "¿Estás seguro de que deseas eliminar esta fila?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    // Si el usuario confirma, se elimina la fila
    if (confirmacion == JOptionPane.YES_OPTION) {
        DefaultTableModel model = (DefaultTableModel) tblEstudiantes.getModel();
        model.removeRow(filaSeleccionada);
        System.out.println("Fila eliminada: " + filaSeleccionada);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      int filaSeleccionada = tblEstudiantes.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para editar.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblEstudiantes.getModel();

    String nombreActual = model.getValueAt(filaSeleccionada, 0).toString();
    String idActual = model.getValueAt(filaSeleccionada, 1).toString();
    String gradoActual = model.getValueAt(filaSeleccionada, 2).toString();

    String nuevoNombre = JOptionPane.showInputDialog("Editar nombre:", nombreActual);
    if (nuevoNombre == null) return; // Para quede Cancelado

    String nuevoID = JOptionPane.showInputDialog("Editar ID:", idActual);
    if (nuevoID == null) return; // Para que Cancelado

    // Verificar si el nuevo ID ya existe en otra fila
    for (int i = 0; i < model.getRowCount(); i++) {
        if (i != filaSeleccionada && nuevoID.equals(model.getValueAt(i, 1).toString())) {
            JOptionPane.showMessageDialog(null, "El ID ya existe en otra fila.");
            return;
        }
    }

    String nuevoGrado = JOptionPane.showInputDialog("Editar grado:", gradoActual);
    if (nuevoGrado == null) return; // Cancelado

    // Actualizar los valores en la tabla
    model.setValueAt(nuevoNombre, filaSeleccionada, 0);
    model.setValueAt(nuevoID, filaSeleccionada, 1);
    model.setValueAt(nuevoGrado, filaSeleccionada, 2);

    System.out.println("Fila editada: " + nuevoNombre + ", " + nuevoID + ", " + nuevoGrado);        
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCarreras().setVisible(true));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables
}
